"""Extra metadata for dramas — network, episodes, synopsis, genre, runtime."""

DRAMA_META = {
    # ── Existing entries (runtime added) ──
    "Queen of Tears": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 80,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "A chaebol heiress and her seemingly perfect husband face a crisis in their marriage, but unexpected events bring them closer together in ways they never imagined.",
    },
    "My Love from the Star": {
        "network": "SBS",
        "episodes": 21,
        "runtime": 60,
        "genre": "Romance, Fantasy, Comedy",
        "synopsis": "An alien who landed on Earth 400 years ago falls in love with a top Hallyu star just before he is about to return to his home planet.",
    },
    "The Glory": {
        "network": "Netflix",
        "episodes": 16,
        "runtime": 55,
        "genre": "Thriller, Drama, Revenge",
        "synopsis": "A woman who was horrifically bullied in high school meticulously plans her revenge against her tormentors over many years.",
    },
    "The Heirs": {
        "network": "SBS",
        "episodes": 20,
        "runtime": 60,
        "genre": "Romance, Drama",
        "synopsis": "The heir to a large conglomerate falls for a poor girl, causing tension with his family and his fiancée from another wealthy family.",
    },
    "Descendants of the Sun": {
        "network": "KBS2",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Action, Comedy",
        "synopsis": "A special forces captain and a doctor fall in love while navigating dangerous situations in a fictional war-torn country.",
    },
    "Crash Landing on You": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 85,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "A South Korean heiress accidentally paraglides into North Korea and falls in love with a North Korean army officer who hides and protects her.",
    },
    "Goblin": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 70,
        "genre": "Romance, Fantasy, Drama",
        "synopsis": "An immortal goblin needs a human bride to end his cursed immortal life, but when he finds her, he doesn't want to die anymore.",
    },
    "Hotel Del Luna": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 75,
        "genre": "Romance, Fantasy, Horror",
        "synopsis": "A mysterious woman who is bound to run a hotel for ghosts teams up with an elite hotelier to manage the establishment and resolve lingering spirits.",
    },
    "It's Okay to Not Be Okay": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 70,
        "genre": "Romance, Drama, Psychological",
        "synopsis": "A psychiatric ward caregiver and an antisocial children's book author heal each other's emotional wounds.",
    },
    "Vincenzo": {
        "network": "tvN",
        "episodes": 20,
        "runtime": 80,
        "genre": "Comedy, Crime, Drama",
        "synopsis": "An Italian-Korean mafia consigliere returns to Seoul where he uses villainous methods to take down an even bigger villain.",
    },
    "Twenty Five Twenty One": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 75,
        "genre": "Romance, Coming-of-age, Drama",
        "synopsis": "Set during the 1998 IMF crisis, a young fencer and a newspaper reporter build a friendship that blossoms into first love.",
    },
    "Hometown Cha-Cha-Cha": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 75,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "A city dentist moves to a seaside village and forms a relationship with the town's beloved jack-of-all-trades handyman.",
    },
    "Strong Woman Do Bong-soon": {
        "network": "JTBC",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Comedy, Action",
        "synopsis": "A petite woman with superhuman strength gets hired as a bodyguard by a CEO and gets entangled in a kidnapping case.",
    },
    "What's Wrong with Secretary Kim": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Comedy",
        "synopsis": "A narcissistic vice chairman struggles to keep his secretary from quitting after nine years, realizing he can't function without her.",
    },
    "Itaewon Class": {
        "network": "JTBC",
        "episodes": 16,
        "runtime": 70,
        "genre": "Drama, Romance, Business",
        "synopsis": "An ex-convict opens a small bar in Itaewon and fights against the food industry giant whose CEO destroyed his family.",
    },
    "Weightlifting Fairy Kim Bok-joo": {
        "network": "MBC",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Comedy, Sports",
        "synopsis": "A college weightlifter navigating first love, rivalry, and self-discovery with the help of her childhood friend, a swimmer.",
    },
    "Mr. Sunshine": {
        "network": "tvN",
        "episodes": 24,
        "runtime": 80,
        "genre": "Historical, Romance, Action",
        "synopsis": "A Korean boy born into slavery escapes to the United States, returning years later as a marine officer during the early 1900s and falling for a noblewoman.",
    },
    "Alchemy of Souls": {
        "network": "tvN",
        "episodes": 30,
        "runtime": 70,
        "genre": "Fantasy, Romance, Action",
        "synopsis": "In a fictional world, a powerful sorceress's soul gets trapped in the body of a blind woman, and she becomes the servant of a young mage from a noble family.",
    },
    "The World of the Married": {
        "network": "JTBC",
        "episodes": 16,
        "runtime": 70,
        "genre": "Drama, Thriller, Melodrama",
        "synopsis": "A successful family doctor discovers her husband's affair and enters a fierce battle of betrayal and revenge.",
    },
    "Nevertheless": {
        "network": "JTBC",
        "episodes": 10,
        "runtime": 60,
        "genre": "Romance, Drama",
        "synopsis": "An art student who doesn't believe in love and a charming sculpture student who doesn't want commitment are drawn to each other despite knowing better.",
    },
    "Moon Lovers: Scarlet Heart Ryeo": {
        "network": "SBS",
        "episodes": 20,
        "runtime": 60,
        "genre": "Historical, Romance, Fantasy",
        "synopsis": "A modern woman is transported back to the Goryeo Dynasty where she becomes entangled in the political struggles and romances of the princes.",
    },
    "My Mister": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 75,
        "genre": "Drama, Slice of Life",
        "synopsis": "A cold, troubled young woman and a middle-aged engineer weighed down by life cross paths and quietly transform each other's existence.",
    },
    "Something in the Rain": {
        "network": "JTBC",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Drama",
        "synopsis": "A woman in her mid-thirties falls in love with her best friend's younger brother, navigating societal expectations and workplace challenges.",
    },
    "Our Beloved Summer": {
        "network": "SBS",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "A former couple who vowed never to see each other again is forced to reunite when a documentary they filmed in high school goes viral.",
    },
    "Pinocchio": {
        "network": "SBS",
        "episodes": 20,
        "runtime": 60,
        "genre": "Romance, Drama",
        "synopsis": "A man seeking truth about his family's tragedy and a woman who hiccups when she lies both become broadcast journalists.",
    },
    "Vagabond": {
        "network": "SBS",
        "episodes": 16,
        "runtime": 70,
        "genre": "Action, Thriller, Espionage",
        "synopsis": "A stuntman stumbles upon a national corruption scandal after a plane crash kills his nephew, teaming up with an intelligence agent to uncover the truth.",
    },
    "SKY Castle": {
        "network": "JTBC",
        "episodes": 20,
        "runtime": 75,
        "genre": "Drama, Thriller, Satire",
        "synopsis": "The ambitious wives in an exclusive residential community go to extreme lengths to get their children into top universities.",
    },
    "Sweet Home": {
        "network": "Netflix",
        "episodes": 10,
        "runtime": 55,
        "genre": "Horror, Thriller, Fantasy",
        "synopsis": "Residents of a run-down apartment building fight to survive as humans transform into monsters driven by their deepest desires.",
    },
    "Lovely Runner": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 70,
        "genre": "Romance, Fantasy, Comedy",
        "synopsis": "A disabled fangirl time-travels back to 2008 to save her favorite idol from his tragic fate, changing both their destinies.",
    },
    "Doctor Slump": {
        "network": "JTBC",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "Two former academic rivals reunite as adults going through the worst times of their lives, finding comfort and love in each other.",
    },
    "The Legend of the Blue Sea": {
        "network": "SBS",
        "episodes": 20,
        "runtime": 65,
        "genre": "Romance, Fantasy, Comedy",
        "synopsis": "A mermaid follows a con artist to Seoul in this modern retelling of a classic Korean folk tale about forbidden love.",
    },
    "Love in the Moonlight": {
        "network": "KBS2",
        "episodes": 18,
        "runtime": 60,
        "genre": "Historical, Romance, Comedy",
        "synopsis": "A woman disguised as a man becomes a eunuch in the Joseon palace and catches the eye of the crown prince.",
    },
    "Doona!": {
        "network": "Netflix",
        "episodes": 9,
        "runtime": 40,
        "genre": "Romance, Drama",
        "synopsis": "A college student falls for his mysterious new neighbor, a former K-pop idol who left the spotlight.",
    },
    "The Beauty Inside": {
        "network": "JTBC",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Fantasy, Comedy",
        "synopsis": "An actress who wakes up in a different body every month falls in love with an airline executive who can't recognize faces.",
    },
    "Another Miss Oh": {
        "network": "tvN",
        "episodes": 18,
        "runtime": 60,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "Two women with the same name get their lives entangled when a man who was supposed to marry one falls for the other.",
    },
    "Why Her": {
        "network": "SBS",
        "episodes": 16,
        "runtime": 70,
        "genre": "Romance, Legal, Thriller",
        "synopsis": "A cold-hearted law professor who lost everything fights to clear her name with the help of a passionate law student.",
    },
    "You Are My Spring": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Mystery, Drama",
        "synopsis": "Hotel concierge and a psychiatrist become entangled in a murder mystery at their apartment building while healing childhood wounds.",
    },
    "True Beauty": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Comedy",
        "synopsis": "A high school student who transforms her looks through makeup gets caught in a love triangle with two classmates who discover her bare-faced secret.",
    },
    "Flower of Evil": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 70,
        "genre": "Thriller, Romance, Mystery",
        "synopsis": "A detective discovers her seemingly perfect husband may be hiding a dark past connected to an unsolved serial murder case.",
    },
    "Business Proposal": {
        "network": "SBS",
        "episodes": 12,
        "runtime": 60,
        "genre": "Romance, Comedy",
        "synopsis": "A woman goes on a blind date pretending to be her friend, only to discover her date is the CEO of the company she works for.",
    },
    "Mr. Queen": {
        "network": "tvN",
        "episodes": 20,
        "runtime": 75,
        "genre": "Historical, Comedy, Romance",
        "synopsis": "A modern-day male chef's soul gets trapped in the body of a Joseon Dynasty queen, leading to hilarious culture clashes.",
    },
    "The Red Sleeve": {
        "network": "MBC",
        "episodes": 17,
        "runtime": 70,
        "genre": "Historical, Romance, Drama",
        "synopsis": "A court lady who values her freedom above all else catches the eye of the crown prince, leading to an epic and tragic romance.",
    },
    "When the Camellia Blooms": {
        "network": "KBS2",
        "episodes": 40,
        "runtime": 35,
        "genre": "Romance, Comedy, Thriller",
        "synopsis": "A single mother running a bar called Camellia finds unexpected love while a serial killer lurks in her small town.",
    },
    "Kill Me, Heal Me": {
        "network": "MBC",
        "episodes": 20,
        "runtime": 60,
        "genre": "Romance, Comedy, Psychological",
        "synopsis": "A third-generation chaebol with dissociative identity disorder secretly seeks treatment from a first-year psychiatry resident.",
    },
    "Extraordinary You": {
        "network": "MBC",
        "episodes": 32,
        "runtime": 35,
        "genre": "Romance, Fantasy, Comedy",
        "synopsis": "A high school student discovers she's a background character in a comic book and fights to change her predetermined storyline.",
    },
    "Cheese in the Trap": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Drama, Psychological",
        "synopsis": "A hardworking college student tries to unravel the mystery behind her seemingly perfect senior's interest in her.",
    },
    "Fight for My Way": {
        "network": "KBS2",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "Four friends in their late twenties struggle to achieve their dreams while navigating work, love, and societal expectations.",
    },
    "My Liberation Notes": {
        "network": "JTBC",
        "episodes": 16,
        "runtime": 70,
        "genre": "Drama, Romance, Slice of Life",
        "synopsis": "Three siblings stuck in a monotonous routine in a rural suburb of Seoul seek liberation from their stifling lives.",
    },
    "Gyeongseong Creature": {
        "network": "Netflix",
        "episodes": 10,
        "runtime": 65,
        "genre": "Thriller, Horror, Historical",
        "synopsis": "In 1945 Japanese-occupied Korea, a wealthy man and a sleuth join forces to investigate a mysterious creature in a hospital.",
    },
    "My Name": {
        "network": "Netflix",
        "episodes": 8,
        "runtime": 50,
        "genre": "Action, Crime, Thriller",
        "synopsis": "A woman joins a drug cartel and infiltrates the police as an undercover agent to avenge her father's death.",
    },
    "Oh My Ghost": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Comedy, Fantasy",
        "synopsis": "A timid assistant chef gets possessed by a lustful ghost who is determined to seduce a star chef to resolve her grudge.",
    },
    "Doom at Your Service": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Fantasy, Drama",
        "synopsis": "A terminally ill woman accidentally summons a god of destruction and makes a dangerous deal that could end the world.",
    },
    "Daily Dose of Sunshine": {
        "network": "Netflix",
        "episodes": 12,
        "runtime": 55,
        "genre": "Drama, Medical, Healing",
        "synopsis": "A nurse in a psychiatric ward navigates the challenges of caring for patients while dealing with her own personal struggles.",
    },
    "Dr. Romantic 3": {
        "network": "SBS",
        "episodes": 16,
        "runtime": 70,
        "genre": "Medical, Romance, Drama",
        "synopsis": "The eccentric genius doctor continues to inspire and challenge young doctors at a small regional hospital.",
    },
    "Temperature of Love": {
        "network": "SBS",
        "episodes": 40,
        "runtime": 35,
        "genre": "Romance, Drama",
        "synopsis": "An aspiring screenwriter and a chef navigate love, ambition, and the passage of time over several years.",
    },
    "Empress Ki": {
        "network": "MBC",
        "episodes": 51,
        "runtime": 60,
        "genre": "Historical, Romance, Political",
        "synopsis": "Based on the true story of a Goryeo woman who becomes empress of the Yuan Dynasty, navigating palace politics and forbidden love.",
    },
    "Secret Garden": {
        "network": "SBS",
        "episodes": 20,
        "runtime": 65,
        "genre": "Romance, Fantasy, Comedy",
        "synopsis": "An arrogant department store CEO and a tough stuntwoman magically swap bodies, leading to unexpected romance.",
    },
    "Dream High": {
        "network": "KBS2",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Comedy, Music",
        "synopsis": "Students at a performing arts high school pursue their dreams of becoming K-pop stars while dealing with rivalry and romance.",
    },
    "Because This Is My First Life": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "A homeless writer and a house-poor programmer enter a contract marriage for practical reasons but develop real feelings.",
    },
    "Love Alarm": {
        "network": "Netflix",
        "episodes": 8,
        "runtime": 50,
        "genre": "Romance, Sci-Fi, Drama",
        "synopsis": "An app that alerts users when someone nearby has feelings for them disrupts the love lives of a group of high school friends.",
    },
    "The Uncanny Counter": {
        "network": "OCN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Action, Fantasy, Thriller",
        "synopsis": "A group of demon hunters who run a noodle restaurant by day battle evil spirits that prey on humans.",
    },
    "Forecasting Love and Weather": {
        "network": "JTBC",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Drama",
        "synopsis": "Meteorologists at the Korea Meteorological Administration navigate unpredictable workplace romances and personal storms.",
    },
    "Mine": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Drama, Mystery, Thriller",
        "synopsis": "Two women married into a wealthy conglomerate family search for their true selves amid secrets, lies, and a murder mystery.",
    },
    # ── New entries for dramas missing metadata ──
    "100 Days My Prince": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 70,
        "genre": "Historical, Romance, Comedy",
        "synopsis": "A Joseon crown prince loses his memory and ends up living as a commoner, where he is forced into a marriage with a village woman.",
    },
    "20th Century Girl": {
        "network": "Netflix",
        "episodes": 1,
        "runtime": 120,
        "genre": "Romance, Coming-of-age",
        "synopsis": "In 1999, a teenage girl tasked with spying on a boy for her best friend ends up falling for him in this nostalgic coming-of-age love story.",
    },
    "365: Repeat the Year": {
        "network": "MBC",
        "episodes": 24,
        "runtime": 35,
        "genre": "Thriller, Mystery, Sci-Fi",
        "synopsis": "Twelve people are given the chance to go back one year in time, but mysterious deaths begin to occur among them.",
    },
    "About Time": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Fantasy, Drama",
        "synopsis": "A woman who can see life clocks discovers that her remaining time stops only when she is with a certain man.",
    },
    "Abyss": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Fantasy, Mystery",
        "synopsis": "Two people are brought back to life by a mysterious marble called Abyss, reborn with appearances that reflect their inner souls.",
    },
    "Agency": {
        "network": "JTBC",
        "episodes": 16,
        "runtime": 70,
        "genre": "Drama, Business",
        "synopsis": "A woman from a humble background claws her way to the top of a prestigious advertising agency, battling corporate politics at every turn.",
    },
    "Angel's Last Mission: Love": {
        "network": "KBS2",
        "episodes": 32,
        "runtime": 35,
        "genre": "Romance, Fantasy, Drama",
        "synopsis": "A mischievous angel is sent on a mission to find true love for a cold-hearted ballerina and ends up falling for her himself.",
    },
    "Anna": {
        "network": "Coupang Play",
        "episodes": 8,
        "runtime": 55,
        "genre": "Drama, Thriller, Psychological",
        "synopsis": "A woman who has been living under a stolen identity for twenty years faces the consequences when her past begins to unravel.",
    },
    "Arthdal Chronicles": {
        "network": "tvN",
        "episodes": 18,
        "runtime": 80,
        "genre": "Fantasy, Historical, Drama",
        "synopsis": "In an ancient mythical land, the inhabitants of a city and its surrounding regions vie for power as civilization dawns.",
    },
    "Ask the Stars": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 75,
        "genre": "Romance, Sci-Fi, Comedy",
        "synopsis": "A space tourist and an astronaut cross paths aboard a space station, where an unexpected romance blooms among the stars.",
    },
    "Backstreet Rookie": {
        "network": "SBS",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Comedy",
        "synopsis": "A convenience store owner hires a quirky part-timer, and their unlikely partnership leads to a budding romance.",
    },
    "Be Melodramatic": {
        "network": "JTBC",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "Three best friends in their thirties navigate careers in the entertainment industry, relationships, and the complexities of modern life in Seoul.",
    },
    "Black Nuns": {
        "network": "Disney+",
        "episodes": 10,
        "runtime": 55,
        "genre": "Action, Thriller, Fantasy",
        "synopsis": "A group of nuns with extraordinary combat abilities fight to protect the world from demonic forces threatening humanity.",
    },
    "Black Salt Dragon": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 70,
        "genre": "Romance, Historical, Fantasy",
        "synopsis": "A half-dragon prince and a court lady navigate palace intrigue and forbidden love in a mythical version of ancient Korea.",
    },
    "City Hunter": {
        "network": "SBS",
        "episodes": 20,
        "runtime": 60,
        "genre": "Action, Romance, Thriller",
        "synopsis": "A young man raised as a weapon of revenge in the golden triangle infiltrates Seoul's political elite to take down those who betrayed his father.",
    },
    "Clean with Passion for Now": {
        "network": "JTBC",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Comedy",
        "synopsis": "A germaphobic CEO of a cleaning company falls for a carefree young woman who couldn't care less about tidiness.",
    },
    "Curtain Call": {
        "network": "KBS2",
        "episodes": 16,
        "runtime": 70,
        "genre": "Drama, Romance",
        "synopsis": "A terminally ill hotel heiress from North Korea wishes to meet her grandson, so a theatre actor is hired to play the role.",
    },
    "Delightfully Deceitful": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Drama, Mystery, Psychological",
        "synopsis": "A genius swindler with antisocial personality disorder and a lawyer join forces, each using the other for their own agenda.",
    },
    "Doctors": {
        "network": "SBS",
        "episodes": 20,
        "runtime": 60,
        "genre": "Medical, Romance, Drama",
        "synopsis": "A troubled teenage delinquent transforms into a successful neurosurgeon and reunites with the teacher who changed her life.",
    },
    "Dr. Romantic 2": {
        "network": "SBS",
        "episodes": 16,
        "runtime": 70,
        "genre": "Medical, Romance, Drama",
        "synopsis": "The eccentric genius doctor Kim Sa-bu takes on two new fellowship doctors at the run-down Doldam Hospital.",
    },
    "Encounter": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 70,
        "genre": "Romance, Melodrama",
        "synopsis": "The daughter-in-law of a powerful political family meets a free-spirited young man while traveling in Cuba, igniting a forbidden romance.",
    },
    "Eve": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Drama, Romance, Revenge",
        "synopsis": "A woman spends thirteen years planning revenge against the chaebol family responsible for her father's death by orchestrating a scandalous divorce lawsuit.",
    },
    "Fated to Love You": {
        "network": "MBC",
        "episodes": 20,
        "runtime": 60,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "An unassuming office worker and a company heir have an accidental one-night stand that leads to pregnancy and an unexpected romance.",
    },
    "Find Me in Your Memory": {
        "network": "MBC",
        "episodes": 32,
        "runtime": 35,
        "genre": "Romance, Drama, Mystery",
        "synopsis": "A news anchor with hyperthymesia who remembers everything falls for a rising actress who has lost her painful memories.",
    },
    "Glitch": {
        "network": "Netflix",
        "episodes": 10,
        "runtime": 45,
        "genre": "Sci-Fi, Comedy, Thriller",
        "synopsis": "A woman who has been seeing UFOs since childhood teams up with a member of a UFO-watching community to find her missing boyfriend.",
    },
    "Go Back Couple": {
        "network": "KBS2",
        "episodes": 12,
        "runtime": 60,
        "genre": "Romance, Comedy, Fantasy",
        "synopsis": "A married couple on the brink of divorce time-travels back to their college days and gets a second chance at life and love.",
    },
    "Goodbye Mr. Black": {
        "network": "MBC",
        "episodes": 20,
        "runtime": 60,
        "genre": "Action, Romance, Revenge",
        "synopsis": "A navy special forces officer is betrayed and left for dead by his best friend, returning years later to seek revenge.",
    },
    "Healer": {
        "network": "KBS2",
        "episodes": 20,
        "runtime": 60,
        "genre": "Action, Romance, Thriller",
        "synopsis": "A mysterious night courier with exceptional fighting skills gets entangled with a reporter as they uncover a decades-old conspiracy.",
    },
    "High Society": {
        "network": "SBS",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Drama",
        "synopsis": "The secret heiress of a department store empire hides her identity and falls for a man who is only interested in dating rich women.",
    },
    "Hospital Ship": {
        "network": "MBC",
        "episodes": 40,
        "runtime": 35,
        "genre": "Medical, Romance, Drama",
        "synopsis": "Three young doctors are assigned to a hospital ship that provides medical care to island communities, learning to work together while healing patients.",
    },
    "Hwang Jini": {
        "network": "KBS2",
        "episodes": 24,
        "runtime": 60,
        "genre": "Historical, Drama, Music",
        "synopsis": "The life of the legendary Joseon-era courtesan and poet Hwang Jini, who defied social norms with her talent and spirit.",
    },
    "I Hear Your Voice": {
        "network": "SBS",
        "episodes": 18,
        "runtime": 60,
        "genre": "Romance, Legal, Fantasy",
        "synopsis": "A young man who can read minds seeks out the woman who testified for him as a child, now a public defender, as a killer from their past returns.",
    },
    "It's Okay, That's Love": {
        "network": "SBS",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Psychological, Drama",
        "synopsis": "A bestselling mystery writer with OCD and a psychiatrist with an aversion to physical intimacy move in together and discover healing through love.",
    },
    "Jealousy Incarnate": {
        "network": "SBS",
        "episodes": 24,
        "runtime": 60,
        "genre": "Romance, Comedy",
        "synopsis": "A weather forecaster with unrequited feelings for a star news anchor finds herself caught in a rivalry between him and his best friend.",
    },
    "Jirisan": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 80,
        "genre": "Mystery, Thriller, Drama",
        "synopsis": "A top ranger at Jiri Mountain National Park and a new recruit uncover mysterious incidents and secrets hidden in the wilderness.",
    },
    "Kairos": {
        "network": "MBC",
        "episodes": 16,
        "runtime": 70,
        "genre": "Thriller, Mystery, Sci-Fi",
        "synopsis": "A man in the present and a woman living one month in the past communicate through phone calls to save each other from tragedy.",
    },
    "Lawless Lawyer": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Action, Legal, Drama",
        "synopsis": "A gangster-turned-lawyer teams up with a by-the-book attorney to take down a corrupt judge who rules a city with an iron fist.",
    },
    "Lies Hidden in My Garden": {
        "network": "tvN",
        "episodes": 8,
        "runtime": 55,
        "genre": "Thriller, Mystery, Drama",
        "synopsis": "Two women whose lives intersect become entangled in a web of secrets and suspicion when a mysterious discovery is made in a garden.",
    },
    "Link: Eat, Love, Kill": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Mystery, Fantasy",
        "synopsis": "A chef begins to feel the emotions of a woman he has never met, leading him to investigate the connection and a mystery from his past.",
    },
    "Little Women": {
        "network": "tvN",
        "episodes": 12,
        "runtime": 75,
        "genre": "Thriller, Mystery, Drama",
        "synopsis": "Three sisters from a poor family become entangled in a conspiracy involving the country's wealthiest family and a slush fund worth billions.",
    },
    "Love Alarm 2": {
        "network": "Netflix",
        "episodes": 6,
        "runtime": 50,
        "genre": "Romance, Sci-Fi, Drama",
        "synopsis": "The love triangle deepens as the Love Alarm app introduces a shield feature and new dilemmas challenge the characters' relationships.",
    },
    "Love Next Door": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 70,
        "genre": "Romance, Comedy",
        "synopsis": "A woman returning home after quitting her dream job reconnects with her childhood neighbor, and their bickering turns into something more.",
    },
    "Love in Contract": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Comedy",
        "synopsis": "A woman who makes a living as a fake wife on contract juggles two very different clients while sorting out her own love life.",
    },
    "Lovestruck in the City": {
        "network": "KakaoTV",
        "episodes": 17,
        "runtime": 30,
        "genre": "Romance, Drama",
        "synopsis": "An architect searches for a free-spirited woman he fell for at the beach who disappeared, presented in a documentary interview format.",
    },
    "Lucky Romance": {
        "network": "MBC",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Comedy",
        "synopsis": "A superstitious woman who believes she must sleep with a man born in the year of the tiger to avoid bad luck targets a genius scientist.",
    },
    "Marry My Husband": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 70,
        "genre": "Romance, Fantasy, Revenge",
        "synopsis": "A woman who dies after catching her husband cheating with her best friend gets a second chance at life and plots to make her friend marry her husband instead.",
    },
    "Melo Is My Nature": {
        "network": "JTBC",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "Three women in their thirties working in the entertainment industry navigate love, friendship, and career while supporting each other.",
    },
    "Memories of the Alhambra": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 70,
        "genre": "Romance, Sci-Fi, Thriller",
        "synopsis": "The CEO of an investment company gets caught up in a mysterious augmented reality game created by a young programmer in Granada, Spain.",
    },
    "Monthly Magazine Home": {
        "network": "JTBC",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "A magazine editor who dreams of owning her own home clashes with her new landlord, a building owner with a cold personality.",
    },
    "Mother": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 70,
        "genre": "Drama, Family",
        "synopsis": "An elementary school teacher discovers one of her students is being abused and impulsively decides to kidnap the child to save her.",
    },
    "My Demon": {
        "network": "SBS",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Fantasy, Comedy",
        "synopsis": "A demon who grants wishes for a price loses his powers and enters a contract marriage with a chaebol heiress.",
    },
    "My Golden Life": {
        "network": "KBS2",
        "episodes": 52,
        "runtime": 35,
        "genre": "Romance, Family, Drama",
        "synopsis": "A hardworking woman discovers she was switched at birth with the daughter of a wealthy family, turning both their lives upside down.",
    },
    "My Happy Ending": {
        "network": "MBC",
        "episodes": 16,
        "runtime": 70,
        "genre": "Thriller, Mystery, Drama",
        "synopsis": "A woman whose life seems perfect on the surface uncovers dark secrets after a stranger's appearance threatens her carefully constructed world.",
    },
    "My Lovely Liar": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Mystery, Comedy",
        "synopsis": "A songwriter who can detect lies meets a man suspected of murder and tries to uncover the truth while falling for him.",
    },
    "Night in Paradise": {
        "network": "Netflix",
        "episodes": 1,
        "runtime": 131,
        "genre": "Crime, Action, Drama",
        "synopsis": "A gangster marked for death flees to Jeju Island where he meets a terminally ill woman, and they form an unlikely bond.",
    },
    "No Gain No Love": {
        "network": "tvN",
        "episodes": 12,
        "runtime": 70,
        "genre": "Romance, Comedy",
        "synopsis": "A practical woman who hates losing anything enters a fake marriage with a convenience store worker to gain a promotion at work.",
    },
    "Now, We Are Breaking Up": {
        "network": "SBS",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Melodrama",
        "synopsis": "A design team leader at a fashion company falls for a freelance photographer, but their past connections complicate the relationship.",
    },
    "Oh My Baby": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Comedy",
        "synopsis": "A career woman in her late thirties who wants a baby but not a husband navigates unconventional paths to motherhood.",
    },
    "Oh My Venus": {
        "network": "KBS2",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Comedy",
        "synopsis": "An overweight lawyer enlists a mysterious personal trainer to help her transform, and the two develop feelings along the way.",
    },
    "Our Blues": {
        "network": "tvN",
        "episodes": 20,
        "runtime": 75,
        "genre": "Drama, Romance, Slice of Life",
        "synopsis": "An ensemble story following the interconnected lives and loves of residents on Jeju Island, each dealing with their own struggles.",
    },
    "Pasta": {
        "network": "MBC",
        "episodes": 20,
        "runtime": 60,
        "genre": "Romance, Comedy",
        "synopsis": "A clumsy kitchen assistant at an Italian restaurant clashes with the newly appointed head chef who fires all female cooks.",
    },
    "Payback": {
        "network": "SBS",
        "episodes": 12,
        "runtime": 70,
        "genre": "Crime, Thriller, Drama",
        "synopsis": "A ruthless money lender and an honest prosecutor join forces to take down a powerful corporate villain exploiting the financial system.",
    },
    "Playful Kiss": {
        "network": "MBC",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Comedy",
        "synopsis": "A not-so-bright girl falls for a genius student and ends up living under the same roof when her house collapses.",
    },
    "Radio Romance": {
        "network": "KBS2",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Drama",
        "synopsis": "A radio scriptwriter reunites with her childhood friend, now a top actor, when he becomes the DJ for her struggling radio show.",
    },
    "Revolver": {
        "network": "Theatrical",
        "episodes": 1,
        "runtime": 118,
        "genre": "Crime, Thriller, Drama",
        "synopsis": "A woman seeks revenge against those who destroyed her life, using her wits and alliances to execute an elaborate plan.",
    },
    "River Where the Moon Rises": {
        "network": "KBS2",
        "episodes": 20,
        "runtime": 60,
        "genre": "Historical, Romance, Action",
        "synopsis": "The legendary Goguryeo princess Pyeong-gang and the general On Dal navigate love and war in a turbulent era of Korean history.",
    },
    "Save Me": {
        "network": "OCN",
        "episodes": 16,
        "runtime": 60,
        "genre": "Thriller, Drama, Psychological",
        "synopsis": "A young woman trapped in a religious cult desperately tries to escape with the help of four young men from her neighborhood.",
    },
    "School 2017": {
        "network": "KBS2",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Coming-of-age, Drama",
        "synopsis": "Students at an elite high school navigate friendship, romance, and injustice while a mysterious student vigilante stirs things up.",
    },
    "Secret Love": {
        "network": "KBS2",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Melodrama",
        "synopsis": "A devoted woman takes the fall for her boyfriend's crime and, after prison, discovers he has married someone else while she was away.",
    },
    "See You in My 19th Life": {
        "network": "tvN",
        "episodes": 12,
        "runtime": 65,
        "genre": "Romance, Fantasy, Drama",
        "synopsis": "A woman who remembers all her past lives tracks down the man she loved in her previous life, determined to reconnect with him.",
    },
    "Sell Your Haunted House": {
        "network": "KBS2",
        "episodes": 16,
        "runtime": 60,
        "genre": "Fantasy, Mystery, Comedy",
        "synopsis": "A real estate agent who can see ghosts and a con artist team up to exorcise spirits from haunted properties and uncover a decades-old mystery.",
    },
    "She Was Pretty": {
        "network": "MBC",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Comedy",
        "synopsis": "A once-beautiful woman whose looks faded reunites with her childhood crush, now a deputy editor, who doesn't recognize her.",
    },
    "Shooting Stars": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Comedy",
        "synopsis": "A PR team leader at an entertainment agency clashes with the top star she manages, their bickering hiding deeper feelings.",
    },
    "Shopping King Louie": {
        "network": "MBC",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Comedy",
        "synopsis": "A shopping-addicted heir who loses his memory is taken in by a kindhearted country girl in Seoul, and they become unlikely roommates.",
    },
    "Sisyphus: The Myth": {
        "network": "JTBC",
        "episodes": 16,
        "runtime": 70,
        "genre": "Sci-Fi, Action, Thriller",
        "synopsis": "A genius engineer discovers a hidden world within our own and teams up with a warrior from the future to save humanity.",
    },
    "Snowdrop": {
        "network": "JTBC",
        "episodes": 16,
        "runtime": 80,
        "genre": "Romance, Political, Thriller",
        "synopsis": "Set in 1987 Seoul, a college student hides a wounded man in her dorm, unaware that he is a North Korean spy embroiled in political turmoil.",
    },
    "Suspicious Partner": {
        "network": "SBS",
        "episodes": 40,
        "runtime": 35,
        "genre": "Romance, Comedy, Legal",
        "synopsis": "A prosecutor and his trainee become entangled in a murder case that binds them together professionally and romantically.",
    },
    "Sweet Home 3": {
        "network": "Netflix",
        "episodes": 8,
        "runtime": 55,
        "genre": "Horror, Thriller, Fantasy",
        "synopsis": "The survivors face a new phase of the monster apocalypse as humanity's last stand brings desperate alliances and ultimate sacrifices.",
    },
    "Tempted": {
        "network": "MBC",
        "episodes": 32,
        "runtime": 35,
        "genre": "Romance, Drama",
        "synopsis": "Three rich friends make a bet to seduce a transfer student, but one of them genuinely falls in love with her.",
    },
    "That Winter, the Wind Blows": {
        "network": "SBS",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Melodrama",
        "synopsis": "A con artist pretends to be the long-lost brother of a blind heiress to steal her fortune, but unexpectedly falls in love with her.",
    },
    "The Atypical Family": {
        "network": "JTBC",
        "episodes": 12,
        "runtime": 65,
        "genre": "Romance, Fantasy, Family",
        "synopsis": "A family with supernatural powers that have weakened over time encounters a mysterious woman who reignites their dormant abilities.",
    },
    "The Crowned Clown": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 70,
        "genre": "Historical, Romance, Drama",
        "synopsis": "A clown who looks exactly like the king is brought in as a body double and must navigate palace politics while protecting those he cares about.",
    },
    "The Escape of the Seven": {
        "network": "SBS",
        "episodes": 16,
        "runtime": 70,
        "genre": "Thriller, Mystery, Revenge",
        "synopsis": "Seven people with dark secrets gather at an isolated location where a deadly game of survival and revenge unfolds.",
    },
    "The Good Doctor": {
        "network": "KBS2",
        "episodes": 20,
        "runtime": 60,
        "genre": "Medical, Drama",
        "synopsis": "A young autistic savant surgeon with extraordinary medical abilities joins a prestigious hospital and faces prejudice from colleagues.",
    },
    "The Greatest Love": {
        "network": "MBC",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Comedy",
        "synopsis": "A washed-up former idol and Korea's most beloved movie star fall for each other despite the scandal it would cause.",
    },
    "The King: Eternal Monarch": {
        "network": "SBS",
        "episodes": 16,
        "runtime": 70,
        "genre": "Romance, Fantasy, Sci-Fi",
        "synopsis": "A modern-day Korean emperor crosses into a parallel universe where he meets a detective, and they must work together to close a door between dimensions.",
    },
    "The Last Princess": {
        "network": "Theatrical",
        "episodes": 1,
        "runtime": 127,
        "genre": "Historical, Drama",
        "synopsis": "Based on the true story of Princess Deok-hye, the last princess of the Korean Empire, and her struggle to return home from Japan.",
    },
    "The Princess' Man": {
        "network": "KBS2",
        "episodes": 24,
        "runtime": 60,
        "genre": "Historical, Romance, Drama",
        "synopsis": "A retelling of Romeo and Juliet set during the Joseon Dynasty, where the children of two rival political factions fall in love.",
    },
    "The Producers": {
        "network": "KBS2",
        "episodes": 12,
        "runtime": 60,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "Behind-the-scenes look at the lives of TV producers and entertainers at a major broadcasting network as they navigate work and romance.",
    },
    "The Story of Park's Marriage Contract": {
        "network": "MBC",
        "episodes": 12,
        "runtime": 65,
        "genre": "Romance, Fantasy, Historical",
        "synopsis": "A Joseon-era woman time-slips to modern Seoul and enters a contract marriage with a man dealing with the aftermath of his divorce.",
    },
    "The Time We Were Not in Love": {
        "network": "SBS",
        "episodes": 16,
        "runtime": 60,
        "genre": "Romance, Comedy",
        "synopsis": "Two childhood best friends who have been inseparable for seventeen years begin to realize their feelings may be more than platonic.",
    },
    "Thirty But Seventeen": {
        "network": "SBS",
        "episodes": 32,
        "runtime": 35,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "A woman wakes up from a thirteen-year coma at age thirty, still mentally seventeen, and must navigate adult life while healing old wounds.",
    },
    "Thirty-Nine": {
        "network": "JTBC",
        "episodes": 12,
        "runtime": 70,
        "genre": "Drama, Romance, Friendship",
        "synopsis": "Three best friends approaching forty navigate love, career, and a devastating health diagnosis that threatens to tear them apart.",
    },
    "To All the Guys Who Loved Me": {
        "network": "KBS2",
        "episodes": 32,
        "runtime": 35,
        "genre": "Romance, Comedy, Sci-Fi",
        "synopsis": "A publishing editor finds herself caught between two very different men: a cold-hearted CEO and a warm-hearted scientist.",
    },
    "Today's Webtoon": {
        "network": "SBS",
        "episodes": 16,
        "runtime": 65,
        "genre": "Drama, Comedy",
        "synopsis": "A former judo athlete pivots to become an editor in a webtoon editorial department, fighting to prove herself in a creative industry.",
    },
    "Tomorrow with You": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Fantasy, Sci-Fi",
        "synopsis": "A time-traveling real estate CEO marries a woman to change his future after seeing a vision of his own death.",
    },
    "Uncontrollably Fond": {
        "network": "KBS2",
        "episodes": 20,
        "runtime": 60,
        "genre": "Romance, Melodrama",
        "synopsis": "A terminally ill top star and a documentary producer reunite years after a painful breakup, reigniting their complicated feelings.",
    },
    "VIP": {
        "network": "SBS",
        "episodes": 32,
        "runtime": 35,
        "genre": "Drama, Romance, Thriller",
        "synopsis": "A dedicated team manager at a department store discovers that her seemingly perfect husband is having an affair with one of her coworkers.",
    },
    "Welcome2Life": {
        "network": "MBC",
        "episodes": 32,
        "runtime": 35,
        "genre": "Fantasy, Legal, Drama",
        "synopsis": "A corrupt lawyer slips into a parallel universe where he is an upstanding prosecutor and must confront the consequences of his past choices.",
    },
    "When My Love Blooms": {
        "network": "tvN",
        "episodes": 16,
        "runtime": 65,
        "genre": "Romance, Melodrama",
        "synopsis": "Two people look back on their passionate college love affair while navigating the pain and responsibilities of their present lives.",
    },
    "While You Were Sleeping": {
        "network": "SBS",
        "episodes": 32,
        "runtime": 35,
        "genre": "Romance, Fantasy, Legal",
        "synopsis": "A woman who sees the future in her dreams meets a prosecutor who shares the same ability, and they work to prevent tragedies before they happen.",
    },
    "Youth of May": {
        "network": "KBS2",
        "episodes": 12,
        "runtime": 65,
        "genre": "Romance, Historical, Drama",
        "synopsis": "Set during the Gwangju Uprising of May 1980, a medical student and a nurse fall in love amid political upheaval and tragedy.",
    },
    "Yumi's Cells": {
        "network": "tvN",
        "episodes": 14,
        "runtime": 50,
        "genre": "Romance, Comedy",
        "synopsis": "An ordinary office worker's love life is told through the perspective of the cells in her brain, who control her emotions and decisions.",
    },
    "Yumi's Cells 2": {
        "network": "tvN",
        "episodes": 14,
        "runtime": 50,
        "genre": "Romance, Comedy",
        "synopsis": "Yumi's cells navigate a new romance and career ambitions as she begins dating a co-worker and pursues her dream of becoming a writer.",
    },
}
