"""Extra metadata for dramas — network, episodes, synopsis, genre."""

DRAMA_META = {
    "Queen of Tears": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "A chaebol heiress and her seemingly perfect husband face a crisis in their marriage, but unexpected events bring them closer together in ways they never imagined.",
    },
    "My Love from the Star": {
        "network": "SBS",
        "episodes": 21,
        "genre": "Romance, Fantasy, Comedy",
        "synopsis": "An alien who landed on Earth 400 years ago falls in love with a top Hallyu star just before he is about to return to his home planet.",
    },
    "The Glory": {
        "network": "Netflix",
        "episodes": 16,
        "genre": "Thriller, Drama, Revenge",
        "synopsis": "A woman who was horrifically bullied in high school meticulously plans her revenge against her tormentors over many years.",
    },
    "The Heirs": {
        "network": "SBS",
        "episodes": 20,
        "genre": "Romance, Drama",
        "synopsis": "The heir to a large conglomerate falls for a poor girl, causing tension with his family and his fiancée from another wealthy family.",
    },
    "Descendants of the Sun": {
        "network": "KBS2",
        "episodes": 16,
        "genre": "Romance, Action, Comedy",
        "synopsis": "A special forces captain and a doctor fall in love while navigating dangerous situations in a fictional war-torn country.",
    },
    "Crash Landing on You": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "A South Korean heiress accidentally paraglides into North Korea and falls in love with a North Korean army officer who hides and protects her.",
    },
    "Goblin": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Romance, Fantasy, Drama",
        "synopsis": "An immortal goblin needs a human bride to end his cursed immortal life, but when he finds her, he doesn't want to die anymore.",
    },
    "Hotel Del Luna": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Romance, Fantasy, Horror",
        "synopsis": "A mysterious woman who is bound to run a hotel for ghosts teams up with an elite hotelier to manage the establishment and resolve lingering spirits.",
    },
    "It's Okay to Not Be Okay": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Romance, Drama, Psychological",
        "synopsis": "A psychiatric ward caregiver and an antisocial children's book author heal each other's emotional wounds.",
    },
    "Vincenzo": {
        "network": "tvN",
        "episodes": 20,
        "genre": "Comedy, Crime, Drama",
        "synopsis": "An Italian-Korean mafia consigliere returns to Seoul where he uses villainous methods to take down an even bigger villain.",
    },
    "Twenty Five Twenty One": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Romance, Coming-of-age, Drama",
        "synopsis": "Set during the 1998 IMF crisis, a young fencer and a newspaper reporter build a friendship that blossoms into first love.",
    },
    "Hometown Cha-Cha-Cha": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "A city dentist moves to a seaside village and forms a relationship with the town's beloved jack-of-all-trades handyman.",
    },
    "Strong Woman Do Bong-soon": {
        "network": "JTBC",
        "episodes": 16,
        "genre": "Romance, Comedy, Action",
        "synopsis": "A petite woman with superhuman strength gets hired as a bodyguard by a CEO and gets entangled in a kidnapping case.",
    },
    "What's Wrong with Secretary Kim": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Romance, Comedy",
        "synopsis": "A narcissistic vice chairman struggles to keep his secretary from quitting after nine years, realizing he can't function without her.",
    },
    "Itaewon Class": {
        "network": "JTBC",
        "episodes": 16,
        "genre": "Drama, Romance, Business",
        "synopsis": "An ex-convict opens a small bar in Itaewon and fights against the food industry giant whose CEO destroyed his family.",
    },
    "Weightlifting Fairy Kim Bok-joo": {
        "network": "MBC",
        "episodes": 16,
        "genre": "Romance, Comedy, Sports",
        "synopsis": "A college weightlifter navigating first love, rivalry, and self-discovery with the help of her childhood friend, a swimmer.",
    },
    "Mr. Sunshine": {
        "network": "tvN",
        "episodes": 24,
        "genre": "Historical, Romance, Action",
        "synopsis": "A Korean boy born into slavery escapes to the United States, returning years later as a marine officer during the early 1900s and falling for a noblewoman.",
    },
    "Alchemy of Souls": {
        "network": "tvN",
        "episodes": 30,
        "genre": "Fantasy, Romance, Action",
        "synopsis": "In a fictional world, a powerful sorceress's soul gets trapped in the body of a blind woman, and she becomes the servant of a young mage from a noble family.",
    },
    "The World of the Married": {
        "network": "JTBC",
        "episodes": 16,
        "genre": "Drama, Thriller, Melodrama",
        "synopsis": "A successful family doctor discovers her husband's affair and enters a fierce battle of betrayal and revenge.",
    },
    "Nevertheless": {
        "network": "JTBC",
        "episodes": 10,
        "genre": "Romance, Drama",
        "synopsis": "An art student who doesn't believe in love and a charming sculpture student who doesn't want commitment are drawn to each other despite knowing better.",
    },
    "Moon Lovers: Scarlet Heart Ryeo": {
        "network": "SBS",
        "episodes": 20,
        "genre": "Historical, Romance, Fantasy",
        "synopsis": "A modern woman is transported back to the Goryeo Dynasty where she becomes entangled in the political struggles and romances of the princes.",
    },
    "My Mister": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Drama, Slice of Life",
        "synopsis": "A cold, troubled young woman and a middle-aged engineer weighed down by life cross paths and quietly transform each other's existence.",
    },
    "Something in the Rain": {
        "network": "JTBC",
        "episodes": 16,
        "genre": "Romance, Drama",
        "synopsis": "A woman in her mid-thirties falls in love with her best friend's younger brother, navigating societal expectations and workplace challenges.",
    },
    "Our Beloved Summer": {
        "network": "SBS",
        "episodes": 16,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "A former couple who vowed never to see each other again is forced to reunite when a documentary they filmed in high school goes viral.",
    },
    "Pinocchio": {
        "network": "SBS",
        "episodes": 20,
        "genre": "Romance, Drama",
        "synopsis": "A man seeking truth about his family's tragedy and a woman who hiccups when she lies both become broadcast journalists.",
    },
    "Vagabond": {
        "network": "SBS",
        "episodes": 16,
        "genre": "Action, Thriller, Espionage",
        "synopsis": "A stuntman stumbles upon a national corruption scandal after a plane crash kills his nephew, teaming up with an intelligence agent to uncover the truth.",
    },
    "SKY Castle": {
        "network": "JTBC",
        "episodes": 20,
        "genre": "Drama, Thriller, Satire",
        "synopsis": "The ambitious wives in an exclusive residential community go to extreme lengths to get their children into top universities.",
    },
    "Sweet Home": {
        "network": "Netflix",
        "episodes": 10,
        "genre": "Horror, Thriller, Fantasy",
        "synopsis": "Residents of a run-down apartment building fight to survive as humans transform into monsters driven by their deepest desires.",
    },
    "Lovely Runner": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Romance, Fantasy, Comedy",
        "synopsis": "A disabled fangirl time-travels back to 2008 to save her favorite idol from his tragic fate, changing both their destinies.",
    },
    "Doctor Slump": {
        "network": "JTBC",
        "episodes": 16,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "Two former academic rivals reunite as adults going through the worst times of their lives, finding comfort and love in each other.",
    },
    "The Legend of the Blue Sea": {
        "network": "SBS",
        "episodes": 20,
        "genre": "Romance, Fantasy, Comedy",
        "synopsis": "A mermaid follows a con artist to Seoul in this modern retelling of a classic Korean folk tale about forbidden love.",
    },
    "Love in the Moonlight": {
        "network": "KBS2",
        "episodes": 18,
        "genre": "Historical, Romance, Comedy",
        "synopsis": "A woman disguised as a man becomes a eunuch in the Joseon palace and catches the eye of the crown prince.",
    },
    "Doona!": {
        "network": "Netflix",
        "episodes": 9,
        "genre": "Romance, Drama",
        "synopsis": "A college student falls for his mysterious new neighbor, a former K-pop idol who left the spotlight.",
    },
    "The Beauty Inside": {
        "network": "JTBC",
        "episodes": 16,
        "genre": "Romance, Fantasy, Comedy",
        "synopsis": "An actress who wakes up in a different body every month falls in love with an airline executive who can't recognize faces.",
    },
    "Another Miss Oh": {
        "network": "tvN",
        "episodes": 18,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "Two women with the same name get their lives entangled when a man who was supposed to marry one falls for the other.",
    },
    "Why Her": {
        "network": "SBS",
        "episodes": 16,
        "genre": "Romance, Legal, Thriller",
        "synopsis": "A cold-hearted law professor who lost everything fights to clear her name with the help of a passionate law student.",
    },
    "You Are My Spring": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Romance, Mystery, Drama",
        "synopsis": "Hotel concierge and a psychiatrist become entangled in a murder mystery at their apartment building while healing childhood wounds.",
    },
    "True Beauty": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Romance, Comedy",
        "synopsis": "A high school student who transforms her looks through makeup gets caught in a love triangle with two classmates who discover her bare-faced secret.",
    },
    "Flower of Evil": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Thriller, Romance, Mystery",
        "synopsis": "A detective discovers her seemingly perfect husband may be hiding a dark past connected to an unsolved serial murder case.",
    },
    "Business Proposal": {
        "network": "SBS",
        "episodes": 12,
        "genre": "Romance, Comedy",
        "synopsis": "A woman goes on a blind date pretending to be her friend, only to discover her date is the CEO of the company she works for.",
    },
    "Mr. Queen": {
        "network": "tvN",
        "episodes": 20,
        "genre": "Historical, Comedy, Romance",
        "synopsis": "A modern-day male chef's soul gets trapped in the body of a Joseon Dynasty queen, leading to hilarious culture clashes.",
    },
    "The Red Sleeve": {
        "network": "MBC",
        "episodes": 17,
        "genre": "Historical, Romance, Drama",
        "synopsis": "A court lady who values her freedom above all else catches the eye of the crown prince, leading to an epic and tragic romance.",
    },
    "When the Camellia Blooms": {
        "network": "KBS2",
        "episodes": 40,
        "genre": "Romance, Comedy, Thriller",
        "synopsis": "A single mother running a bar called Camellia finds unexpected love while a serial killer lurks in her small town.",
    },
    "Kill Me, Heal Me": {
        "network": "MBC",
        "episodes": 20,
        "genre": "Romance, Comedy, Psychological",
        "synopsis": "A third-generation chaebol with dissociative identity disorder secretly seeks treatment from a first-year psychiatry resident.",
    },
    "Extraordinary You": {
        "network": "MBC",
        "episodes": 32,
        "genre": "Romance, Fantasy, Comedy",
        "synopsis": "A high school student discovers she's a background character in a comic book and fights to change her predetermined storyline.",
    },
    "Cheese in the Trap": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Romance, Drama, Psychological",
        "synopsis": "A hardworking college student tries to unravel the mystery behind her seemingly perfect senior's interest in her.",
    },
    "Fight for My Way": {
        "network": "KBS2",
        "episodes": 16,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "Four friends in their late twenties struggle to achieve their dreams while navigating work, love, and societal expectations.",
    },
    "My Liberation Notes": {
        "network": "JTBC",
        "episodes": 16,
        "genre": "Drama, Romance, Slice of Life",
        "synopsis": "Three siblings stuck in a monotonous routine in a rural suburb of Seoul seek liberation from their stifling lives.",
    },
    "Gyeongseong Creature": {
        "network": "Netflix",
        "episodes": 10,
        "genre": "Thriller, Horror, Historical",
        "synopsis": "In 1945 Japanese-occupied Korea, a wealthy man and a sleuth join forces to investigate a mysterious creature in a hospital.",
    },
    "My Name": {
        "network": "Netflix",
        "episodes": 8,
        "genre": "Action, Crime, Thriller",
        "synopsis": "A woman joins a drug cartel and infiltrates the police as an undercover agent to avenge her father's death.",
    },
    "Oh My Ghost": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Romance, Comedy, Fantasy",
        "synopsis": "A timid assistant chef gets possessed by a lustful ghost who is determined to seduce a star chef to resolve her grudge.",
    },
    "Doom at Your Service": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Romance, Fantasy, Drama",
        "synopsis": "A terminally ill woman accidentally summons a god of destruction and makes a dangerous deal that could end the world.",
    },
    "Daily Dose of Sunshine": {
        "network": "Netflix",
        "episodes": 12,
        "genre": "Drama, Medical, Healing",
        "synopsis": "A nurse in a psychiatric ward navigates the challenges of caring for patients while dealing with her own personal struggles.",
    },
    "Dr. Romantic 3": {
        "network": "SBS",
        "episodes": 16,
        "genre": "Medical, Romance, Drama",
        "synopsis": "The eccentric genius doctor continues to inspire and challenge young doctors at a small regional hospital.",
    },
    "Temperature of Love": {
        "network": "SBS",
        "episodes": 40,
        "genre": "Romance, Drama",
        "synopsis": "An aspiring screenwriter and a chef navigate love, ambition, and the passage of time over several years.",
    },
    "Empress Ki": {
        "network": "MBC",
        "episodes": 51,
        "genre": "Historical, Romance, Political",
        "synopsis": "Based on the true story of a Goryeo woman who becomes empress of the Yuan Dynasty, navigating palace politics and forbidden love.",
    },
    "Secret Garden": {
        "network": "SBS",
        "episodes": 20,
        "genre": "Romance, Fantasy, Comedy",
        "synopsis": "An arrogant department store CEO and a tough stuntwoman magically swap bodies, leading to unexpected romance.",
    },
    "Dream High": {
        "network": "KBS2",
        "episodes": 16,
        "genre": "Romance, Comedy, Music",
        "synopsis": "Students at a performing arts high school pursue their dreams of becoming K-pop stars while dealing with rivalry and romance.",
    },
    "Because This Is My First Life": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Romance, Comedy, Drama",
        "synopsis": "A homeless writer and a house-poor programmer enter a contract marriage for practical reasons but develop real feelings.",
    },
    "Love Alarm": {
        "network": "Netflix",
        "episodes": 8,
        "genre": "Romance, Sci-Fi, Drama",
        "synopsis": "An app that alerts users when someone nearby has feelings for them disrupts the love lives of a group of high school friends.",
    },
    "The Uncanny Counter": {
        "network": "OCN",
        "episodes": 16,
        "genre": "Action, Fantasy, Thriller",
        "synopsis": "A group of demon hunters who run a noodle restaurant by day battle evil spirits that prey on humans.",
    },
    "Forecasting Love and Weather": {
        "network": "JTBC",
        "episodes": 16,
        "genre": "Romance, Drama",
        "synopsis": "Meteorologists at the Korea Meteorological Administration navigate unpredictable workplace romances and personal storms.",
    },
    "Mine": {
        "network": "tvN",
        "episodes": 16,
        "genre": "Drama, Mystery, Thriller",
        "synopsis": "Two women married into a wealthy conglomerate family search for their true selves amid secrets, lies, and a murder mystery.",
    },
}
