"""Seed the database with initial actress data."""
from database import actresses_collection

SEED_DATA = [
    {
        "name": "Kim Ji-won", "known": "Queen of Tears", "genre": "Romance", "year": 2024, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/250327_%EA%B9%80%EC%A7%80%EC%9B%90_BVLGARI_4.png/330px-250327_%EA%B9%80%EC%A7%80%EC%9B%90_BVLGARI_4.png",
        "birthDate": "October 19, 1992", "birthPlace": "Seoul, South Korea", "agency": "SidusHQ",
        "dramas": [
            {"title": "Queen of Tears", "year": 2024, "role": "Hong Hae-in"},
            {"title": "My Liberation Notes", "year": 2022, "role": "Yeom Mi-jeong"},
            {"title": "Lovestruck in the City", "year": 2020, "role": "Lee Eun-oh"},
            {"title": "Arthdal Chronicles", "year": 2019, "role": "Tanya"},
            {"title": "Fight for My Way", "year": 2017, "role": "Choi Ae-ra"},
            {"title": "Descendants of the Sun", "year": 2016, "role": "Yoon Myeong-ju"},
        ],
        "awards": ["Baeksang Arts Award - Best Actress (TV)", "Grand Prize (Daesang) - SBS Drama Awards 2024", "Top Excellence Award - tvN"],
    },
    {
        "name": "Jun Ji-hyun", "known": "My Love from the Star", "genre": "Fantasy", "year": 2014, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/20250902_Jun_Ji-hyun_%28%EC%A0%84%EC%A7%80%ED%98%84%29.png/330px-20250902_Jun_Ji-hyun_%28%EC%A0%84%EC%A7%80%ED%98%84%29.png",
        "birthDate": "October 30, 1981", "birthPlace": "Seoul, South Korea", "agency": "Culture Depot",
        "dramas": [
            {"title": "Jirisan", "year": 2021, "role": "Seo Yi-gang"},
            {"title": "The Legend of the Blue Sea", "year": 2016, "role": "Shim Cheong"},
            {"title": "My Love from the Star", "year": 2013, "role": "Cheon Song-yi"},
        ],
        "awards": ["Grand Prize (Daesang) - SBS Drama Awards", "Baeksang Arts Award - Most Popular Actress", "Blue Dragon Film Award - Best Actress"],
    },
    {
        "name": "Song Hye-kyo", "known": "The Glory", "genre": "Thriller", "year": 2023, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Song_Hye_Kyo_2025_%EC%86%A1%ED%98%9C%EA%B5%90_04.jpg/330px-Song_Hye_Kyo_2025_%EC%86%A1%ED%98%9C%EA%B5%90_04.jpg",
        "birthDate": "November 22, 1981", "birthPlace": "Daegu, South Korea", "agency": "UAA",
        "dramas": [
            {"title": "Black Nuns", "year": 2025, "role": "Lead"},
            {"title": "The Glory", "year": 2022, "role": "Moon Dong-eun"},
            {"title": "Now, We Are Breaking Up", "year": 2021, "role": "Ha Young-eun"},
            {"title": "Encounter", "year": 2018, "role": "Cha Soo-hyun"},
            {"title": "Descendants of the Sun", "year": 2016, "role": "Kang Mo-yeon"},
            {"title": "That Winter, the Wind Blows", "year": 2013, "role": "Oh Young"},
        ],
        "awards": ["Baeksang Arts Award - Best Actress (TV)", "Grand Prize (Daesang) - KBS Drama Awards", "Korea Drama Awards - Best Actress"],
    },
    {
        "name": "Park Shin-hye", "known": "The Heirs", "genre": "Romance", "year": 2013, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Park_Shin-hye_in_April_2025.png/330px-Park_Shin-hye_in_April_2025.png",
        "birthDate": "February 18, 1990", "birthPlace": "Gwangju, South Korea", "agency": "SALT Entertainment",
        "dramas": [
            {"title": "Doctor Slump", "year": 2024, "role": "Nam Ha-neul"},
            {"title": "Sisyphus: The Myth", "year": 2021, "role": "Kang Seo-hae"},
            {"title": "Memories of the Alhambra", "year": 2018, "role": "Jung Hee-joo"},
            {"title": "Doctors", "year": 2016, "role": "Yoo Hye-jung"},
            {"title": "Pinocchio", "year": 2014, "role": "Choi In-ha"},
            {"title": "The Heirs", "year": 2013, "role": "Cha Eun-sang"},
        ],
        "awards": ["Top Excellence Award - SBS Drama Awards", "Best Actress - APAN Star Awards", "Korean Popular Culture Award"],
    },
    {
        "name": "Bae Suzy", "known": "While You Were Sleeping", "genre": "Fantasy", "year": 2017, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/20241128_Bae_Suzy_CELINE_photocall_%28cropped%29.jpg/330px-20241128_Bae_Suzy_CELINE_photocall_%28cropped%29.jpg",
        "birthDate": "October 10, 1994", "birthPlace": "Gwangju, South Korea", "agency": "Management SOOP",
        "dramas": [
            {"title": "Doona!", "year": 2023, "role": "Lee Doona"},
            {"title": "Anna", "year": 2022, "role": "Anna/Yumi"},
            {"title": "Vagabond", "year": 2019, "role": "Go Hae-ri"},
            {"title": "While You Were Sleeping", "year": 2017, "role": "Nam Hong-joo"},
            {"title": "Uncontrollably Fond", "year": 2016, "role": "Noh Eul"},
        ],
        "awards": ["Baeksang Arts Award - Most Popular Actress", "Top Excellence Award - SBS Drama Awards", "Asia Artist Award - Best Actress"],
    },
    {
        "name": "IU (Lee Ji-eun)", "known": "Hotel Del Luna", "genre": "Fantasy", "year": 2019, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/IU_at_Blue_Dragon_Series_Awards_on_18072025_%2810%29.png/330px-IU_at_Blue_Dragon_Series_Awards_on_18072025_%2810%29.png",
        "birthDate": "May 16, 1993", "birthPlace": "Seoul, South Korea", "agency": "EDAM Entertainment",
        "dramas": [
            {"title": "Hotel Del Luna", "year": 2019, "role": "Jang Man-wol"},
            {"title": "My Mister", "year": 2018, "role": "Lee Ji-an"},
            {"title": "Moon Lovers: Scarlet Heart Ryeo", "year": 2016, "role": "Hae Soo"},
            {"title": "The Producers", "year": 2015, "role": "Cindy"},
            {"title": "Dream High", "year": 2011, "role": "Kim Pil-sook"},
        ],
        "awards": ["Grand Prize (Daesang) - tvN10 Awards", "Best Actress - Korea Drama Awards", "Golden Disc Award - Digital Bonsang"],
    },
    {
        "name": "Kim So-hyun", "known": "Love Alarm", "genre": "Romance", "year": 2019, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Kim_So-hyun_Airport_Departure_February_2025.png/330px-Kim_So-hyun_Airport_Departure_February_2025.png",
        "birthDate": "June 4, 1999", "birthPlace": "Canberra, Australia", "agency": "Culture Depot",
        "dramas": [
            {"title": "My Lovely Liar", "year": 2023, "role": "Mok Sol-hee"},
            {"title": "Love Alarm 2", "year": 2021, "role": "Kim Jo-jo"},
            {"title": "River Where the Moon Rises", "year": 2021, "role": "Pyeong-gang"},
            {"title": "Love Alarm", "year": 2019, "role": "Kim Jo-jo"},
            {"title": "Radio Romance", "year": 2018, "role": "Song Geu-rim"},
        ],
        "awards": ["Best Young Actress - KBS Drama Awards", "Best Child Actress - Baeksang Arts Awards", "Excellence Award - MBC Drama Awards"],
    },
    {
        "name": "Moon Ga-young", "known": "True Beauty", "genre": "Romance", "year": 2020, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/20250319_Moon_Ga-young_at_a_photo_call_event_02.jpg/330px-20250319_Moon_Ga-young_at_a_photo_call_event_02.jpg",
        "birthDate": "July 10, 1996", "birthPlace": "Karlsruhe, Germany", "agency": "KeyEast",
        "dramas": [
            {"title": "Black Salt Dragon", "year": 2024, "role": "Lead"},
            {"title": "Link: Eat, Love, Kill", "year": 2022, "role": "Noh Da-hyun"},
            {"title": "True Beauty", "year": 2020, "role": "Lim Ju-gyeong"},
            {"title": "Find Me in Your Memory", "year": 2020, "role": "Yeo Ha-jin"},
            {"title": "Tempted", "year": 2018, "role": "Eun Tae-hee"},
        ],
        "awards": ["Best New Actress - tvN", "Rising Star Award - Asia Artist Awards", "Best Couple Award - KBS Drama Awards"],
    },
    {
        "name": "Han So-hee", "known": "My Name", "genre": "Action", "year": 2021, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Han_So-Hee_at_the_2025_Toronto_International_Film_Festival_%28cropped%29.jpg/330px-Han_So-Hee_at_the_2025_Toronto_International_Film_Festival_%28cropped%29.jpg",
        "birthDate": "November 18, 1994", "birthPlace": "Ulsan, South Korea", "agency": "9ato Entertainment",
        "dramas": [
            {"title": "Gyeongseong Creature", "year": 2023, "role": "Yoon Chae-ok"},
            {"title": "My Name", "year": 2021, "role": "Yoon Ji-woo"},
            {"title": "Nevertheless", "year": 2021, "role": "Yoo Na-bi"},
            {"title": "The World of the Married", "year": 2020, "role": "Yeo Da-kyung"},
            {"title": "Abyss", "year": 2019, "role": "Go Se-yeon"},
        ],
        "awards": ["Best New Actress - Baeksang Arts Awards", "Popularity Award - APAN Star Awards", "Excellence Award - JTBC Drama Awards"],
    },
    {
        "name": "Kim Yoo-jung", "known": "Backstreet Rookie", "genre": "Comedy", "year": 2020, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Kim_Yoo-jung_in_October_2025_02.png/330px-Kim_Yoo-jung_in_October_2025_02.png",
        "birthDate": "September 22, 1999", "birthPlace": "Seoul, South Korea", "agency": "Awesome ENT",
        "dramas": [
            {"title": "My Demon", "year": 2023, "role": "Do Do-hee"},
            {"title": "20th Century Girl", "year": 2022, "role": "Na Bo-ra"},
            {"title": "Backstreet Rookie", "year": 2020, "role": "Jung Saet-byul"},
            {"title": "Clean with Passion for Now", "year": 2018, "role": "Gil O-sol"},
            {"title": "Love in the Moonlight", "year": 2016, "role": "Hong Ra-on"},
        ],
        "awards": ["Best Young Actress - Baeksang Arts Awards", "Best Actress - KBS Drama Awards", "Top Excellence Award - SBS Drama Awards"],
    },
    {
        "name": "Shin Min-a", "known": "Hometown Cha-Cha-Cha", "genre": "Romance", "year": 2021, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Shin_Min-a_in_September_2024.png/330px-Shin_Min-a_in_September_2024.png",
        "birthDate": "April 5, 1984", "birthPlace": "Seoul, South Korea", "agency": "AM Entertainment",
        "dramas": [
            {"title": "No Gain No Love", "year": 2024, "role": "Son Hae-yeong"},
            {"title": "Our Blues", "year": 2022, "role": "Min Seon-a"},
            {"title": "Hometown Cha-Cha-Cha", "year": 2021, "role": "Yoon Hye-jin"},
            {"title": "Tomorrow with You", "year": 2017, "role": "Song Ma-rin"},
            {"title": "Oh My Venus", "year": 2015, "role": "Kang Joo-eun"},
        ],
        "awards": ["Top Excellence Award - tvN", "Best Actress - Korea Drama Awards", "Grand Prize - Model Awards"],
    },
    {
        "name": "Son Ye-jin", "known": "Crash Landing on You", "genre": "Romance", "year": 2020, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Son_Ye-jin_at_the_2025_Blue_Dragon_Film_Awards_3.png/330px-Son_Ye-jin_at_the_2025_Blue_Dragon_Film_Awards_3.png",
        "birthDate": "January 11, 1982", "birthPlace": "Daegu, South Korea", "agency": "MSteam Entertainment",
        "dramas": [
            {"title": "Thirty-Nine", "year": 2022, "role": "Cha Mi-jo"},
            {"title": "Crash Landing on You", "year": 2019, "role": "Yoon Se-ri"},
            {"title": "Something in the Rain", "year": 2018, "role": "Yoon Jin-a"},
            {"title": "The Last Princess", "year": 2016, "role": "Princess Deok-hye"},
        ],
        "awards": ["Grand Prize (Daesang) - tvN", "Baeksang Arts Award - Best Actress", "Blue Dragon Film Award - Best Actress"],
    },
    {
        "name": "Kim Tae-ri", "known": "Twenty Five Twenty One", "genre": "Romance", "year": 2022, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Kim_Tae-ri_PRADA_BEAUTY_Photo_call_August_2024.png/330px-Kim_Tae-ri_PRADA_BEAUTY_Photo_call_August_2024.png",
        "birthDate": "April 24, 1990", "birthPlace": "Seoul, South Korea", "agency": "Management mmm",
        "dramas": [
            {"title": "Revolver", "year": 2024, "role": "Ha Soo-young"},
            {"title": "Twenty Five Twenty One", "year": 2022, "role": "Na Hee-do"},
            {"title": "Mr. Sunshine", "year": 2018, "role": "Go Ae-shin"},
        ],
        "awards": ["Baeksang Arts Award - Best New Actress (Film)", "Blue Dragon Film Award - Best New Actress", "Top Excellence Award - tvN"],
    },
    {
        "name": "Jeon Yeo-been", "known": "Vincenzo", "genre": "Action", "year": 2021, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Jeon_Yeo-been_at_the_2nd_Blue_Dragon_Series_Awards.jpg/330px-Jeon_Yeo-been_at_the_2nd_Blue_Dragon_Series_Awards.jpg",
        "birthDate": "July 26, 1989", "birthPlace": "Seoul, South Korea", "agency": "Management SOOP",
        "dramas": [
            {"title": "Glitch", "year": 2022, "role": "Hong Ji-hyo"},
            {"title": "Vincenzo", "year": 2021, "role": "Hong Cha-young"},
            {"title": "Night in Paradise", "year": 2020, "role": "Jae-yeon"},
            {"title": "Be Melodramatic", "year": 2019, "role": "Lee Eun-jung"},
        ],
        "awards": ["Best New Actress - Baeksang Arts Awards", "Best Actress - Buil Film Awards", "Rising Star Award - Asia Artist Awards"],
    },
    {
        "name": "Lim Ji-yeon", "known": "The Glory", "genre": "Thriller", "year": 2023, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Lim_Ji-yeon_in_October_2025.png/330px-Lim_Ji-yeon_in_October_2025.png",
        "birthDate": "July 23, 1990", "birthPlace": "Seoul, South Korea", "agency": "Artist Company",
        "dramas": [
            {"title": "The Glory", "year": 2022, "role": "Park Yeon-jin"},
            {"title": "Lies Hidden in My Garden", "year": 2023, "role": "Chu Sang-eun"},
            {"title": "Welcome2Life", "year": 2019, "role": "Ra Si-on"},
            {"title": "High Society", "year": 2015, "role": "Jang Yoon-ha"},
        ],
        "awards": ["Best Supporting Actress - Baeksang Arts Awards", "Excellence Award - Netflix Series Awards", "Best Villain - Brand of the Year Awards"],
    },
    {
        "name": "Go Min-si", "known": "Sweet Home", "genre": "Horror", "year": 2020, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Go_Min-si_2021.png/330px-Go_Min-si_2021.png",
        "birthDate": "April 15, 1995", "birthPlace": "Seoul, South Korea", "agency": "IOK Company",
        "dramas": [
            {"title": "Sweet Home 3", "year": 2024, "role": "Lee Eun-hyuk"},
            {"title": "Youth of May", "year": 2021, "role": "Kim Myung-hee"},
            {"title": "Sweet Home", "year": 2020, "role": "Lee Eun-yoo"},
            {"title": "Love Alarm", "year": 2019, "role": "Kim Sun-oh's friend"},
        ],
        "awards": ["Best New Actress - KBS Drama Awards", "Rising Star Award - Asia Contents Awards"],
    },
    {
        "name": "Park Bo-young", "known": "Strong Woman Do Bong-soon", "genre": "Comedy", "year": 2017, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/20240719_Park_Bo-young_3rd_Blue_Dragon_Series_Awards.jpg/330px-20240719_Park_Bo-young_3rd_Blue_Dragon_Series_Awards.jpg",
        "birthDate": "February 12, 1990", "birthPlace": "Jeungpyeong, South Korea", "agency": "BH Entertainment",
        "dramas": [
            {"title": "Daily Dose of Sunshine", "year": 2023, "role": "Jung Da-eun"},
            {"title": "Doom at Your Service", "year": 2021, "role": "Tak Dong-kyung"},
            {"title": "Strong Woman Do Bong-soon", "year": 2017, "role": "Do Bong-soon"},
            {"title": "Oh My Ghost", "year": 2015, "role": "Na Bong-sun"},
        ],
        "awards": ["Top Excellence Award - JTBC Drama Awards", "Best Actress - Korea Drama Awards", "Blue Dragon Film Award - Best New Actress"],
    },
    {
        "name": "Seo Ye-ji", "known": "It's Okay to Not Be Okay", "genre": "Romance", "year": 2020, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Seo_Yea-ji_in_August_2024.png/330px-Seo_Yea-ji_in_August_2024.png",
        "birthDate": "April 6, 1990", "birthPlace": "Seoul, South Korea", "agency": "Gold Medalist",
        "dramas": [
            {"title": "Eve", "year": 2022, "role": "Lee Ra-el"},
            {"title": "It's Okay to Not Be Okay", "year": 2020, "role": "Ko Moon-young"},
            {"title": "Lawless Lawyer", "year": 2018, "role": "Ha Jae-yi"},
            {"title": "Save Me", "year": 2017, "role": "Im Sang-mi"},
        ],
        "awards": ["Best Actress - Brand of the Year Awards", "Top Excellence Award - tvN", "Asia Celebrity Award"],
    },
    {
        "name": "Nam Ji-hyun", "known": "Little Women", "genre": "Thriller", "year": 2022, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Nam_Ji-hyun_in_July_2024.png/330px-Nam_Ji-hyun_in_July_2024.png",
        "birthDate": "September 17, 1995", "birthPlace": "Seoul, South Korea", "agency": "Management SOOP",
        "dramas": [
            {"title": "Little Women", "year": 2022, "role": "Oh In-kyung"},
            {"title": "365: Repeat the Year", "year": 2020, "role": "Shin Ga-hyun"},
            {"title": "100 Days My Prince", "year": 2018, "role": "Yool/Hong-shim"},
            {"title": "Suspicious Partner", "year": 2017, "role": "Eun Bong-hee"},
            {"title": "Shopping King Louie", "year": 2016, "role": "Ko Bok-sil"},
        ],
        "awards": ["Best New Actress - MBC Drama Awards", "Excellence Award - tvN", "Best Young Actress - SBS Drama Awards"],
    },
    {
        "name": "Kim Se-jeong", "known": "Business Proposal", "genre": "Comedy", "year": 2022, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Kim_Sejeong_in_June_2025.png/330px-Kim_Sejeong_in_June_2025.png",
        "birthDate": "August 28, 1996", "birthPlace": "Gimje, South Korea", "agency": "Jellyfish Entertainment",
        "dramas": [
            {"title": "Today's Webtoon", "year": 2022, "role": "On Ma-eum"},
            {"title": "Business Proposal", "year": 2022, "role": "Shin Ha-ri"},
            {"title": "The Uncanny Counter", "year": 2020, "role": "Do Ha-na"},
            {"title": "School 2017", "year": 2017, "role": "Ra Eun-ho"},
        ],
        "awards": ["Best New Actress - SBS Drama Awards", "Top Excellence Award - KBS Drama Awards", "Popularity Award - Asia Artist Awards"],
    },
    {
        "name": "Park Min-young", "known": "What's Wrong with Secretary Kim", "genre": "Romance", "year": 2018, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/20250625_Park_Min-young_TAG_Heuer_PhotoCall.jpg/330px-20250625_Park_Min-young_TAG_Heuer_PhotoCall.jpg",
        "birthDate": "March 4, 1986", "birthPlace": "Seoul, South Korea", "agency": "Hook Entertainment",
        "dramas": [
            {"title": "Marry My Husband", "year": 2024, "role": "Kang Ji-won"},
            {"title": "Love in Contract", "year": 2022, "role": "Choi Sang-eun"},
            {"title": "Forecasting Love and Weather", "year": 2022, "role": "Jin Ha-kyung"},
            {"title": "What's Wrong with Secretary Kim", "year": 2018, "role": "Kim Mi-so"},
            {"title": "Healer", "year": 2014, "role": "Chae Young-shin"},
            {"title": "City Hunter", "year": 2011, "role": "Kim Na-na"},
        ],
        "awards": ["Top Excellence Award - tvN", "Best Actress - APAN Star Awards", "Excellence Award - SBS Drama Awards"],
    },
    {
        "name": "Shin Hye-sun", "known": "Mr. Queen", "genre": "Comedy", "year": 2021, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Shin_Hye-sun_in_April_2024.png/330px-Shin_Hye-sun_in_April_2024.png",
        "birthDate": "August 31, 1989", "birthPlace": "Seoul, South Korea", "agency": "YNK Entertainment",
        "dramas": [
            {"title": "See You in My 19th Life", "year": 2023, "role": "Ban Ji-eum"},
            {"title": "Mr. Queen", "year": 2020, "role": "Kim So-yong/Jang Bong-hwan"},
            {"title": "Angel's Last Mission: Love", "year": 2019, "role": "Lee Yeon-seo"},
            {"title": "Thirty But Seventeen", "year": 2018, "role": "Woo Seo-ri"},
            {"title": "My Golden Life", "year": 2017, "role": "Seo Ji-an"},
        ],
        "awards": ["Grand Prize (Daesang) - tvN Drama Awards", "Top Excellence Award - KBS Drama Awards", "Best Actress - APAN Star Awards"],
    },
    {
        "name": "Kim Go-eun", "known": "Goblin", "genre": "Fantasy", "year": 2017, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Kim_Go-eun_at_the_2024_Toronto_International_Film_Festival_2.jpg/330px-Kim_Go-eun_at_the_2024_Toronto_International_Film_Festival_2.jpg",
        "birthDate": "July 2, 1991", "birthPlace": "Seoul, South Korea", "agency": "BH Entertainment",
        "dramas": [
            {"title": "Little Women", "year": 2022, "role": "Oh In-joo"},
            {"title": "Yumi's Cells 2", "year": 2022, "role": "Kim Yumi"},
            {"title": "Yumi's Cells", "year": 2021, "role": "Kim Yumi"},
            {"title": "The King: Eternal Monarch", "year": 2020, "role": "Jung Tae-eul"},
            {"title": "Goblin", "year": 2016, "role": "Ji Eun-tak"},
            {"title": "Cheese in the Trap", "year": 2016, "role": "Hong Seol"},
        ],
        "awards": ["Blue Dragon Film Award - Best New Actress", "Baeksang Arts Award - Best New Actress", "Grand Bell Award - Best Actress"],
    },
    {
        "name": "Lee Sung-kyung", "known": "Weightlifting Fairy Kim Bok-joo", "genre": "Romance", "year": 2016, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Lee_Sung-kyung_in_March_2025.png/330px-Lee_Sung-kyung_in_March_2025.png",
        "birthDate": "August 10, 1990", "birthPlace": "Goyang, South Korea", "agency": "YG Entertainment",
        "dramas": [
            {"title": "Shooting Stars", "year": 2022, "role": "Oh Han-byeol"},
            {"title": "Dr. Romantic 2", "year": 2020, "role": "Cha Eun-jae"},
            {"title": "About Time", "year": 2018, "role": "Choi Michaela"},
            {"title": "Weightlifting Fairy Kim Bok-joo", "year": 2016, "role": "Kim Bok-joo"},
            {"title": "Doctors", "year": 2016, "role": "Jin Seo-woo"},
            {"title": "Cheese in the Trap", "year": 2016, "role": "Baek In-ha"},
        ],
        "awards": ["Best New Actress - MBC Drama Awards", "Best Couple Award - MBC Drama Awards", "Rising Star Award - Asia Artist Awards"],
    },
    {
        "name": "Jung So-min", "known": "Because This Is My First Life", "genre": "Romance", "year": 2017, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Jung_So-min_in_March_2025.png/330px-Jung_So-min_in_March_2025.png",
        "birthDate": "March 16, 1989", "birthPlace": "Seoul, South Korea", "agency": "Jellyfish Entertainment",
        "dramas": [
            {"title": "Love Next Door", "year": 2024, "role": "Bae Seok-ryu"},
            {"title": "Alchemy of Souls", "year": 2022, "role": "Mu-deok/Jin Bu-yeon"},
            {"title": "Monthly Magazine Home", "year": 2021, "role": "Na Young-won"},
            {"title": "Because This Is My First Life", "year": 2017, "role": "Yoon Ji-ho"},
            {"title": "Playful Kiss", "year": 2010, "role": "Oh Ha-ni"},
        ],
        "awards": ["Best New Actress - KBS Drama Awards", "Excellence Award - tvN", "Top Excellence Award - jTBC Drama Awards"],
    },
    {
        "name": "Chun Woo-hee", "known": "The Atypical Family", "genre": "Fantasy", "year": 2024, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Chun_Woo-hee_in_July_2024_02.jpg/330px-Chun_Woo-hee_in_July_2024_02.jpg",
        "birthDate": "April 20, 1987", "birthPlace": "Daegu, South Korea", "agency": "Management SOOP",
        "dramas": [
            {"title": "The Atypical Family", "year": 2024, "role": "Do Da-hae"},
            {"title": "Delightfully Deceitful", "year": 2023, "role": "Lee Ro-um"},
            {"title": "Melo Is My Nature", "year": 2019, "role": "Lee Eun-jung"},
        ],
        "awards": ["Best Actress - Blue Dragon Film Awards", "Best New Actress - Baeksang Arts Awards (Film)", "Best Actress - Busan Film Critics Awards"],
    },
    {
        "name": "Lee Se-young", "known": "The Red Sleeve", "genre": "Historical", "year": 2021, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Lee_Se-young_at_Incheon_International_Airport_on_28022025_%282%29.jpg/330px-Lee_Se-young_at_Incheon_International_Airport_on_28022025_%282%29.jpg",
        "birthDate": "December 20, 1992", "birthPlace": "Seoul, South Korea", "agency": "Fly Up Entertainment",
        "dramas": [
            {"title": "The Story of Park's Marriage Contract", "year": 2023, "role": "Park Yeon-woo"},
            {"title": "The Red Sleeve", "year": 2021, "role": "Seong Deok-im"},
            {"title": "Kairos", "year": 2020, "role": "Han Ae-ri"},
            {"title": "The Crowned Clown", "year": 2019, "role": "Yoo So-woon"},
        ],
        "awards": ["Grand Prize (Daesang) - MBC Drama Awards", "Best Actress - APAN Star Awards", "Excellence Award - MBC Drama Awards"],
    },
    {
        "name": "Moon Chae-won", "known": "Flower of Evil", "genre": "Thriller", "year": 2020, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Moon_Chae-won_in_2024_-_1.png/330px-Moon_Chae-won_in_2024_-_1.png",
        "birthDate": "November 13, 1986", "birthPlace": "Daegu, South Korea", "agency": "Namoo Actors",
        "dramas": [
            {"title": "Payback", "year": 2023, "role": "Park Jun-gyeong"},
            {"title": "Flower of Evil", "year": 2020, "role": "Cha Ji-won"},
            {"title": "Goodbye Mr. Black", "year": 2016, "role": "Swan/Min Sun-young"},
            {"title": "The Good Doctor", "year": 2013, "role": "Yoon Seo-jung"},
            {"title": "The Princess' Man", "year": 2011, "role": "Se-ryung"},
        ],
        "awards": ["Top Excellence Award - tvN", "Best Actress - KBS Drama Awards", "Excellence Award - SBS Drama Awards"],
    },
    {
        "name": "Kim Da-mi", "known": "Itaewon Class", "genre": "Drama", "year": 2020, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/20240410_Kim_Da-mi_%28%EA%B9%80%EB%8B%A4%EB%AF%B8%29.jpg/330px-20240410_Kim_Da-mi_%28%EA%B9%80%EB%8B%A4%EB%AF%B8%29.jpg",
        "birthDate": "April 9, 1995", "birthPlace": "Seoul, South Korea", "agency": "Andmarq",
        "dramas": [
            {"title": "Our Beloved Summer", "year": 2021, "role": "Kook Yeon-su"},
            {"title": "Itaewon Class", "year": 2020, "role": "Jo Yi-seo"},
        ],
        "awards": ["Blue Dragon Film Award - Best New Actress", "Best New Actress - Baeksang Arts Awards", "Rookie Award - Wildflower Film Awards"],
    },
    {
        "name": "Hwang Jung-eum", "known": "Kill Me, Heal Me", "genre": "Romance", "year": 2015, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Hwang_Jung-eum_in_March_2024.png/330px-Hwang_Jung-eum_in_March_2024.png",
        "birthDate": "January 25, 1985", "birthPlace": "Seoul, South Korea", "agency": "C-JeS Entertainment",
        "dramas": [
            {"title": "The Escape of the Seven", "year": 2023, "role": "Han Monica"},
            {"title": "To All the Guys Who Loved Me", "year": 2020, "role": "Seo Hyun-joo"},
            {"title": "Lucky Romance", "year": 2016, "role": "Shim Bo-nui"},
            {"title": "She Was Pretty", "year": 2015, "role": "Kim Hye-jin"},
            {"title": "Kill Me, Heal Me", "year": 2015, "role": "Oh Ri-jin"},
            {"title": "Secret Love", "year": 2013, "role": "Kang Yoo-jung"},
        ],
        "awards": ["Top Excellence Award - MBC Drama Awards", "Best Actress - SBS Drama Awards", "Excellence Award - KBS Drama Awards"],
    },
    {
        "name": "Kim Hye-yoon", "known": "Lovely Runner", "genre": "Romance", "year": 2024, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/20250820_Kim_Hye_Yoon_%28%EA%B9%80%ED%98%9C%EC%9C%A4%29.png/330px-20250820_Kim_Hye_Yoon_%28%EA%B9%80%ED%98%9C%EC%9C%A4%29.png",
        "birthDate": "November 10, 1996", "birthPlace": "Seoul, South Korea", "agency": "Artist Company",
        "dramas": [
            {"title": "Lovely Runner", "year": 2024, "role": "Im Sol"},
            {"title": "Snowdrop", "year": 2021, "role": "Kye Bun-ok"},
            {"title": "Extraordinary You", "year": 2019, "role": "Eun Dan-oh"},
            {"title": "SKY Castle", "year": 2018, "role": "Kang Ye-seo"},
        ],
        "awards": ["Grand Prize (Daesang) - tvN Drama Awards 2024", "Best New Actress - Baeksang Arts Awards", "Top Excellence Award - MBC Drama Awards"],
    },
    {
        "name": "Lee Bo-young", "known": "Mine", "genre": "Thriller", "year": 2021, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Lee_Bo-young_in_March_2024.png/330px-Lee_Bo-young_in_March_2024.png",
        "birthDate": "January 12, 1979", "birthPlace": "Daejeon, South Korea", "agency": "JS Pictures",
        "dramas": [
            {"title": "Agency", "year": 2023, "role": "Go Ah-in"},
            {"title": "Mine", "year": 2021, "role": "Seo Hee-soo"},
            {"title": "When My Love Blooms", "year": 2020, "role": "Han Jae-hyun"},
            {"title": "Mother", "year": 2018, "role": "Soo-jin"},
            {"title": "I Hear Your Voice", "year": 2013, "role": "Jang Hye-sung"},
        ],
        "awards": ["Grand Prize (Daesang) - SBS Drama Awards", "Top Excellence Award - tvN", "Best Actress - Baeksang Arts Awards"],
    },
    {
        "name": "Gong Hyo-jin", "known": "When the Camellia Blooms", "genre": "Romance", "year": 2019, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Gong_Hyo-jin_in_October_2024.png/330px-Gong_Hyo-jin_in_October_2024.png",
        "birthDate": "April 4, 1980", "birthPlace": "Seoul, South Korea", "agency": "Soop Management",
        "dramas": [
            {"title": "Ask the Stars", "year": 2024, "role": "Eve Kim"},
            {"title": "When the Camellia Blooms", "year": 2019, "role": "Oh Dong-baek"},
            {"title": "Jealousy Incarnate", "year": 2016, "role": "Pyo Na-ri"},
            {"title": "It's Okay, That's Love", "year": 2014, "role": "Ji Hae-soo"},
            {"title": "The Greatest Love", "year": 2011, "role": "Gu Ae-jung"},
            {"title": "Pasta", "year": 2010, "role": "Seo Yoo-kyung"},
        ],
        "awards": ["Grand Prize (Daesang) - KBS Drama Awards", "Baeksang Arts Award - Best Actress (TV)", "Top Excellence Award - SBS Drama Awards"],
    },
    {
        "name": "Ha Ji-won", "known": "Empress Ki", "genre": "Historical", "year": 2014, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Ha_Ji-won_in_September_2025.png/330px-Ha_Ji-won_in_September_2025.png",
        "birthDate": "June 28, 1978", "birthPlace": "Seoul, South Korea", "agency": "Haewadal Entertainment",
        "dramas": [
            {"title": "Curtain Call", "year": 2022, "role": "Park Se-yeon"},
            {"title": "Hospital Ship", "year": 2017, "role": "Song Eun-jae"},
            {"title": "The Time We Were Not in Love", "year": 2015, "role": "Oh Ha-na"},
            {"title": "Empress Ki", "year": 2013, "role": "Ki Seungnyang"},
            {"title": "Secret Garden", "year": 2010, "role": "Gil Ra-im"},
            {"title": "Hwang Jini", "year": 2006, "role": "Hwang Jini"},
        ],
        "awards": ["Grand Prize (Daesang) - MBC Drama Awards", "Top Excellence Award - KBS Drama Awards", "Best Actress - Baeksang Arts Awards"],
    },
    {
        "name": "Jang Na-ra", "known": "Sell Your Haunted House", "genre": "Fantasy", "year": 2021, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Jang_Na-ra_in_July_2024.png/330px-Jang_Na-ra_in_July_2024.png",
        "birthDate": "March 18, 1981", "birthPlace": "Seoul, South Korea", "agency": "Lawon Entertainment",
        "dramas": [
            {"title": "My Happy Ending", "year": 2023, "role": "Seo Jae-won"},
            {"title": "Sell Your Haunted House", "year": 2021, "role": "Hong Ji-a"},
            {"title": "Oh My Baby", "year": 2020, "role": "Jang Ha-ri"},
            {"title": "VIP", "year": 2019, "role": "Na Jung-sun"},
            {"title": "Go Back Couple", "year": 2017, "role": "Ma Jin-joo"},
            {"title": "Fated to Love You", "year": 2014, "role": "Kim Mi-young"},
        ],
        "awards": ["Top Excellence Award - KBS Drama Awards", "Best Actress - SBS Drama Awards", "Grand Prize (Daesang) - MBC Drama Awards"],
    },
    {
        "name": "Seo Hyun-jin", "known": "The Beauty Inside", "genre": "Romance", "year": 2018, "tier": None,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Seo_Hyun-jin_in_February_2025.png/330px-Seo_Hyun-jin_in_February_2025.png",
        "birthDate": "February 27, 1985", "birthPlace": "Daejeon, South Korea", "agency": "Management SOOP",
        "dramas": [
            {"title": "The Beauty Inside", "year": 2018, "role": "Han Se-gye"},
            {"title": "Another Miss Oh", "year": 2016, "role": "Oh Hae-young"},
            {"title": "Temperature of Love", "year": 2017, "role": "Lee Hyun-soo"},
            {"title": "You Are My Spring", "year": 2021, "role": "Kang Da-jung"},
            {"title": "Why Her", "year": 2022, "role": "Oh Soo-jae"},
            {"title": "Dr. Romantic 3", "year": 2023, "role": "Cha Eun-jae"},
        ],
        "awards": ["SBS Drama Awards - Grand Prize (Another Miss Oh, 2016)", "SBS Drama Awards - Best Actress (The Beauty Inside, 2018)", "Korea Drama Awards - Best Actress (Another Miss Oh, 2016)", "Seoul International Drama Awards - Outstanding Korean Actress (2017)"],
    },
]


def seed():
    actresses_collection.drop()
    actresses_collection.insert_many(SEED_DATA)
    print(f"Seeded {len(SEED_DATA)} actresses into MongoDB.")
    # Also populate gallery images and drama posters
    from update_gallery import update as update_gallery
    update_gallery()
    from update_posters import update as update_posters
    update_posters()


if __name__ == "__main__":
    seed()
